main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: projects/
    weight: 20
  - name: Publications
    url: /#papers
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: Team
    url: team/
    weight: 50
  - name: News
    url: /#news
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70
